### ISSUE TITLE
[FEATURE] When a Mount Pod is deleted, the CSI driver should update the Mount Pod

### ISSUE THREAD

**Issue by SonglinLife** [juicedata/juicefs-csi-driver#1037]
In current code, when deleted a **in-use**(has reference annnotation) mount pod, the csi driver would create a new mount pod with same configuration:

Here is the relevant code:

https://github.com/juicedata/juicefs-csi-driver/blob/master/pkg/controller/pod_driver.go#L376C1-L384C6

```go
var newPod = &corev1.Pod{
	ObjectMeta: metav1.ObjectMeta{
		Name:        pod.Name,
		Namespace:   pod.Namespace,
		Labels:      pod.Labels,
		Annotations: annotation,
	},
	Spec: pod.Spec,
}
```

However, In many case, deleting a mount pod means that we want to update the mount pod, such as using a new Juicefs client image.

**Comment by 0zero-r** [comment]
currently, it will apply the new spec based on the config  https://github.com/juicedata/juicefs-csi-driver/blob/337603e1897f87b5946265baa28ee148255b8d0d/pkg/controller/pod_driver.go#L387-L389

but, there will be an issue in the CE version that causes it to not take effect, fixed in https://github.com/juicedata/juicefs-csi-driver/pull/1014

a fixed version will be released in this week.

**Comment by zxh326** [comment]
currently, it will apply the new spec based on the config  https://github.com/juicedata/juicefs-csi-driver/blob/337603e1897f87b5946265baa28ee148255b8d0d/pkg/controller/pod_driver.go#L387-L389

but, there will be an issue in the CE version that causes it to not take effect, fixed in https://github.com/juicedata/juicefs-csi-driver/pull/1014

a fixed version will be released in this week.

**Comment by SonglinLife** [comment]
Thanks for your efforts. I had this question due to the old version of the code.
