### ISSUE TITLE
Does the csi driver support serverless kubernetes like ASK?

### ISSUE THREAD

**Issue by ZhengRui** [juicedata/juicefs-csi-driver#150]
I am trying out in alibaba cloud ASK cluster, and after I do `kubectl apply -f k8s.yaml`, the `csi-controller` pod has status `ProviderFailed`, and describing the pod it shows `Message: The specified parameter HostPathVolume is not valid`. I guess it's because of `hostPath` is being used in `k8s.yaml` ? So my question is does juicefs's csi-driver support ASK? Thanks.

**Comment by ZhengRui** [comment]
from alicloud ack and ask csi documentations, indeed it seems ack support hostPath but ask not yet, wondering is it possible to modify `k8s.yaml` file to make it work for ask like Alibaba's official `csi-privisioner`?

**Comment by zwwhdls** [comment]
Hi @ZhengRui ,

ASK did not support node related functions, such as DaemonSet and HostPath, but JuiceFS csi driver is deployed as DaemonSet and uses hostPath /var/lib/kubelet shared with kubelet. Furthermore, The nodes of the ASK cluster are virtual in witch pod can't reach kubelet. However csi driver needs to register to kubelet and kubelet needs to call csi plugin when PV is created. So JuiceFS csi driver dosen't support ASK. 

I will close this issue, thanks.

**Comment by ZhengRui** [comment]
thanks for confirmation, is there plan to support serverless k8s? @zwwhdls

**Comment by zwwhdls** [comment]
Hi @ZhengRui , 

JuiceFS CSI driver can't support serverless k8s, because of its no node related functions such as Daemonset, HostPath, fuse... However, you can use JuiceFS SDK instead. Please refer to this document: https://github.com/juicedata/juicefs/blob/main/docs/en/hadoop_java_sdk.md

If you have any other requirements or ideas, welcome to raise issue.
