### ISSUE TITLE
problem of mount name too long

### ISSUE THREAD

**Issue by fishincat** [juicedata/juicefs-csi-driver#162]
When Mound Pod Name is longer than 63, it will be Truncated to 63. And the Pod Will Created.
But you can't get pod info by original name. So the mount action will be failed.

1. SHOULD check the length of PodName, return failed once it is longer than 63.

2. In our production env, the NodeName offen is very long, and the PodName can be overlong very easily.
Can we use status.hostIP instead of spec.nodeName to format PodName ? I don't know if it will cause any new problems!

**Comment by zwwhdls** [comment]
Hi @fishincat , thanks for your feedback.

I found that Kubernetes limits pod name 253 characters: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/

I also tested it in my cluster. When pod name is greater than 63 and less than 253, it can be created without name being truncated. And when pod name is greater than 253, it can't be created:

```
The Pod "kube-node-3-ddddddddddddddddddddd1234567889123456789012345678ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddkube-node-3-ddddddddddddddddddddd1234567889123456789012345678dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd" is invalid: metadata.name: Invalid value: "kube-node-3-ddddddddddddddddddddd1234567889123456789012345678ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddkube-node-3-ddddddddddddddddddddd1234567889123456789012345678dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd": must be no more than 253 characters
```

So, as the result above, it will fail when pod name is too long and it's expected. Considering compatibility and readability, I think it is not suitable to take node ip instead of node name.

By the way, what's your Kubernetes version that "When Mound Pod Name is longer than 63, it will be Truncated to 63. And the Pod Will Created." happened?

**Comment by fishincat** [comment]
kubelet/kubelet_pods.go
```
 412 // truncatePodHostnameIfNeeded truncates the pod hostname if it's longer than 63 chars.
 413 func truncatePodHostnameIfNeeded(podName, hostname string) (string, error) {
 414     // Cap hostname at 63 chars (specification is 64bytes which is 63 chars and the null terminating char).
 415     const hostnameMaxLen = 63
 416     if len(hostname) <= hostnameMaxLen {
 417         return hostname, nil
 418     }
 419     truncated := hostname[:hostnameMaxLen]
 420     klog.ErrorS(nil, "Hostname for pod was too long, truncated it", "podName", podName, "hostnameMaxLen", hostnameMaxLen, "truncatedHostname", truncated)
 421     // hostname should not end with '-' or '.'
 422     truncated = strings.TrimRight(truncated, "-.")
 423     if len(truncated) == 0 {
 424         // This should never happen.
 425         return "", fmt.Errorf("hostname for pod %q was invalid: %q", podName, hostname)
 426     }
 427     return truncated, nil
 428 }

```
the latest version.

**Comment by zwwhdls** [comment]
From the `truncatePodHostnameIfNeeded` code, it's pod.spec.hostname truncated, not podName. We didn't use the mount pod hostname, we use the host which mount pod is scheduled. I think it doesn't matter when pod hostname is truncated.

**Comment by fishincat** [comment]
I see, I made a mistake. thx
