### ISSUE TITLE
update storage backend configurations

### ISSUE THREAD

**Issue by Iced-Sun** [juicedata/juicefs-csi-driver#168]
Commit 86aca1e forces the `--no-update` option. What should we do if the access credential is rotated or revoked, or any other configuration is changed?

**Comment by zwwhdls** [comment]
Hi @Iced-Sun , you can run cmd `juicefs format ` without `--no-update` outside k8s cluster.

**Comment by Iced-Sun** [comment]
Sure this is what we do now, which seems a bit unintuitive to me. By the way, what is the intention of commit 86aca1e? Avoiding possible accidental mis-configurations?

**Comment by zwwhdls** [comment]
Hi @Iced-Sun , that's because `juicefs format` cmd option `compress` default value is `lz4` in early version. Later the default value was changed to `none` i.e. no compression. But `juicefs format` will not succeed when `compress` is changed, so we add `--no-update` in `juicefs format` to avoiding this error. 

We will find a way to support updating access credential later. Thanks.
