### ISSUE TITLE
[FEATURES] add sentinel password option

### ISSUE THREAD

**Issue by fakemoon** [juicedata/juicefs-csi-driver#201]
**What feature you'd like to add:**
Currently JuiceFS supports using redis meta engine with sentinel. But there is no way to pass sentinel password in redis URL.
On baremetal I could set env SENTINEL_PASSWORD which juicefs would read to connect to sentinel.
But on CSI driver, I cannot achieve that by simply editing values.yaml or the helm chart.

**Why is this feature needed:**
It would be useful to use CSI driver with redis sentinel meta engine

**Comment by zwwhdls** [comment]
Hi @fakemoon ,

You can set env in mount pod refer to [this](https://github.com/juicedata/juicefs-csi-driver/blob/master/docs/en/examples/config-and-env.md).

Also, you can set sentinel password in metaurl refer to [this](https://github.com/juicedata/juicefs/blob/main/docs/en/redis_best_practices.md#high-availability).

We recommend setting sentinel password in metaurl. Because metaurl is in k8s Secret, it's not saved in plaintext. Env in mount pod will set in pod yaml in plaintext.

**Comment by fakemoon** [comment]
> Hi @fakemoon ,
> 
> You can set env in mount pod refer to [this](https://github.com/juicedata/juicefs-csi-driver/blob/master/docs/en/examples/config-and-env.md).
> 
> Also, you can set sentinel password in metaurl refer to [this](https://github.com/juicedata/juicefs/blob/main/docs/en/redis_best_practices.md#high-availability).
> 
> We recommend setting sentinel password in metaurl. Because metaurl is in k8s Secret, it's not saved in plaintext. Env in mount pod will set in pod yaml in plaintext.

Thank you for this guidance! I’ll try both methods.
