### ISSUE TITLE
[BUG] mount fails when k8s nodes have different kubelet rootdir config

### ISSUE THREAD

**Issue by krislint** [juicedata/juicefs-csi-driver#554]
## Question

Before asking a question, make sure you have:

- Reviewed relevant Kubernetes information: Google your error messages and look at K8s docs.
- Searched open and closed [GitHub issues](https://github.com/juicedata/juicefs-csi-driver/issues?utf8=%E2%9C%93&q=is%3Aissue)
- Read the documentation: [JuiceFS CSI Driver Doc](https://juicefs.com/docs/csi/introduction/)

**What help did you want**:

![image](https://user-images.githubusercontent.com/31123389/215443890-7be596e1-8619-4892-a2c9-6a4a96a79ff8.png)
why root-dir not support soft link
some k8s node may different config 

**Environment**:
- JuiceFS CSI Driver version (which image tag did your CSI Driver use): v0.17.5
- Kubernetes version (e.g. `kubectl version`): 1.15.0
- Object storage (cloud provider and region): s3
- Metadata engine info (version, cloud provider managed or self maintained): redis

**Comment by krislint** [comment]
I use soft link to make /data01/kubelet the same as /data01/k8s/kubelet

**Comment by krislint** [comment]
if I config an error root-dir the CSI driver will not found

**Comment by zwwhdls** [comment]
@krislint Hi, thanks for your feedback. 

JuiceFS CSI raise error when kubelet root-dir configured in csi daemonset not equal the actual kubelet root-dir. That's to prevent users from not setting the correct rootdir. 

Actually, when rootdirs in different nodes are not the same, using soft link to make each nodes has the same config is the best way. We will fix this issue asap. Thanks!

**Comment by zwwhdls** [comment]
@krislint Hi, after further research we found that soft link of kubelet root-dir can not work. 

That's because container path which to be mounted is under actual kubelet root-dir (for example `/data0/kubelet`), but csi container can not reach it but only the soft link (`/data0/k8s/kubelet`). When csi bind mount container target path (`/data0/kubelet/pods/xxxx/volumes/...`) into JuiceFS volume, it will not take effect in host.
