### ISSUE TITLE
Unzip files too slowly [QUESTION] 

### ISSUE THREAD

**Issue by marklee1982** [juicedata/juicefs-csi-driver#585]
## Question
I want to unzip a file in demo pod, nfs vs juicesfs.
file: ILSVRC2012_img_val.tar size: 6.3G count: 5w jpeg files.
                  nfs              juicefs pvc
cp              49.9             52.74
unzip         205.1           911.6 
delete        15.6             27.4 
how can we optimization it.

Before asking a question, make sure you have:

- Reviewed relevant Kubernetes information: Google your error messages and look at K8s docs.
- Searched open and closed [GitHub issues](https://github.com/juicedata/juicefs-csi-driver/issues?utf8=%E2%9C%93&q=is%3Aissue)
- Read the documentation: [JuiceFS CSI Driver Doc](https://juicefs.com/docs/csi/introduction/)

**What help did you want**:

**Environment**:
- JuiceFS CSI Driver version (which image tag did your CSI Driver use):juicefs-csi-driver-0.14.1
- Kubernetes version (e.g. `kubectl version`):v1.20.11
- Object storage (cloud provider and region): minio
- Metadata engine info (version, cloud provider managed or self maintained): redis
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):  10G
- Others:

**Comment by zwwhdls** [comment]
Hi @marklee1982 , it is a known issue. 

[`--writeback`](https://juicefs.com/docs/community/internals/io_processing/#writeback-mode) mode helps in unzip issue. But we do not recommend `writeback` in CSI. Because JuiceFS client will upload data to object storage asynchronously and mount pod (running JuiceFS client) is not a stateful pod, it will exit when application exits which will result in data lost. 

In this case, it is recommended that unzip files to local file system and move them to JuiceFS concurrently.

**Comment by zwwhdls** [comment]
more message in https://github.com/juicedata/juicefs-csi-driver/pull/588
