### ISSUE TITLE
[BUG] long namespace is not supported

### ISSUE THREAD

**Issue by davies** [juicedata/juicefs-csi-driver#854]
When namespace is long, the generated pod name may exceed limit, we should only use the part of it when it's too long.

**Comment by timfeirg** [comment]
the problem is with annotation key, not mount pod name (see [code](https://github.com/juicedata/juicefs-csi-driver/blob/feature/monitor/pkg/juicefs/mount/pod_mount.go#L533)):

```
Warning  FailedMount  11s (x7 over 43s)  kubelet            MountVolume.SetUp failed for volume “pv-ws-prod01awsuswest2wssys-storage-rsync-deployment-0” : rpc error: code = Internal desc = Could not mount juicefs: Pod “storage-rsync-deployment-5698ddb754-4h65k” is invalid: metadata.annotations: Invalid value: “juicefs-mountpod-pv-ws-prod01awsuswest2wssys-storage-rsync-deployment-0”: name part must be no more than 63 characters
```

previously I've discussed with @Hexilee , but since this issue re-occurs, we might have to cut this prefix? or make this annotation optional? (continue even if fail?)
